language: node_js
os: linux
dist: xenial
node_js:
  - 11
  - 12
  - 13
  - 14
cache:
  directories:
    - node_modules
before_install:
  - npm update
install:
  - npm install
script:
  - npm test
before_deploy:
  - npm run build
deploy:
  provider: npm
  skip_cleanup: true
  email: transbankdevelopers@continuum.cl
  api_token:
    secure: Ac72wnf865My0/hPxZXqd6foqiK7LUap6k7GlAkjfhl/NBh7T2feyeFcpgWCHVWm4s3JQoV8wSmLKUz3+hz1hgHRtz7JnY/5VU/NIuuMjXa7zvXkecYDCi8hpxtlFLwhexr3vS6/Y5n+LZBAyoMTK3IrCKRhlsucTQn/nw7dpKwLQcFSocsaX4dFp2o5cY2zfr42iKJlQquUApTU6kU5cPFoq6mfKwQT7/O1UA3NOJkQWx+Xj/v+A1lPtn/hc8CTuAsEN1pUV9ucBK6/QN9BpkHo013UBNbTfJfSUH8dHfAP7OfcD0OQSiX1wnnG3JYE0NonUZp+GhzYEz5XBAUS/6nJJ2TRyw5QoVdnIKzYw19Np9hOmaG9/gjqKyve5SdNwCkurufAz5ubYQbxI+KtCkkJ1T3Q0EpGxzpmW/9xQx/vRpZEWhev0Xk0yjKg6/hVI6v2jf7wYo3k2K9AGDWD+xXmAysVKty8Vc/PkEqjhb1Jsm5h0Z0SKj6eqNChTwnLfWl/9zxsKRuDKKV0CoSdDJ+bohlYUTYuAtlu3TylxNlEor8FDXz3NVTnHZjQT9L3EKwkaxIvXLt6/mn4a/QTiA0kh/KvpJ4zCxHCkzTSskKxo8wLeUJOcQ0mmmMgojxpw/kmS+aU60Nx3L0I5KNYLwV/A59UOkcXNYwsLSop59A=
  on:
    tags: true
    repo: TransbankDevelopers/transbank-sdk-nodejs
    node_js: 11
